package com.blackflower.curriculumcreator;

import com.blackflower.curriculumcreator.jpa.model.Admin;
import com.blackflower.curriculumcreator.jpa.model.Instructor;
import com.blackflower.curriculumcreator.jpa.model.Person;
import com.blackflower.curriculumcreator.jpa.model.Student;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author emirs
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("C:\\Users\\emirs\\Desktop\\pics\\chalkboard.jpg");
        Image imgFit = icon.getImage().getScaledInstance(930, 571, Image.SCALE_AREA_AVERAGING);
        icon.setImage(imgFit);
        
        //bgImageLayer.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 242, 295, 43));
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        Person account = MainFrame.instance.getAccount();

        if (account == null) {
            MainFrame.instance.setPage(MainFrame.instance.getLoginPage());
        } else if (account instanceof Admin) {
            MainFrame.instance.setPage(MainFrame.instance.getAdminHomePage());
            MainFrame.instance.login();
        } else if (account instanceof Instructor) {
            MainFrame.instance.setPage(MainFrame.instance.getInstructorHomePage());
            MainFrame.instance.login();
        } else if (account instanceof Student) {
            MainFrame.instance.setPage(MainFrame.instance.getStudentHomePage());
            MainFrame.instance.login();
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Unclassified Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables
}
