package com.blackflower.curriculumcreator;

import com.blackflower.curriculumcreator.jpa.model.Admin;
import com.blackflower.curriculumcreator.jpa.model.Instructor;
import com.blackflower.curriculumcreator.jpa.model.Person;
import com.blackflower.curriculumcreator.jpa.model.Student;
import javax.swing.JOptionPane;

/**
 *
 * @author emirs
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();
        infoText = new javax.swing.JLabel();

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        infoText.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        infoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoText.setText("WELCOME BACK: ALİ NİZAM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoText, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(infoText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        Person account = MainFrame.instance.getAccount();

        if (account == null) {
            MainFrame.instance.setPage(MainFrame.instance.getLoginPage());
        } else if (account instanceof Admin) {
            MainFrame.instance.setPage(MainFrame.instance.getAdminHomePage());
            MainFrame.instance.login();
        } else if (account instanceof Instructor) {
            MainFrame.instance.setPage(MainFrame.instance.getInstructorHomePage());
            MainFrame.instance.login();
        } else if (account instanceof Student) {
            MainFrame.instance.setPage(MainFrame.instance.getStudentHomePage());
            MainFrame.instance.login();
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Unclassified Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoText;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables
}
